package Modelo;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Mesa Value Object.
  * This class is value object representing database table mesa
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Mesa implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int id;
    private String codigo_mesa;
    private String estado;
    private int id_restaurante;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Mesa () {

    }

    public Mesa (String codigo_mesa) {

          this.codigo_mesa = codigo_mesa;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getId() {
          return this.id;
    }
    public void setId(int idIn) {
          this.id = idIn;
    }

    public String getCodigo_mesa() {
          return this.codigo_mesa;
    }
    public void setCodigo_mesa(String codigo_mesaIn) {
          this.codigo_mesa = codigo_mesaIn;
    }

    public String getEstado() {
          return this.estado;
    }
    public void setEstado(String estadoIn) {
          this.estado = estadoIn;
    }

    public int getId_restaurante() {
          return this.id_restaurante;
    }
    public void setId_restaurante(int id_restauranteIn) {
          this.id_restaurante = id_restauranteIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int idIn,
          String codigo_mesaIn,
          String estadoIn,
          int id_restauranteIn) {
          this.id = idIn;
          this.codigo_mesa = codigo_mesaIn;
          this.estado = estadoIn;
          this.id_restaurante = id_restauranteIn;
    }


    /** 
     * hasEqualMapping-method will compare two Mesa instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Mesa valueObject) {

          if (valueObject.getId() != this.id) {
                    return(false);
          }
          if (this.codigo_mesa == null) {
                    if (valueObject.getCodigo_mesa() != null)
                           return(false);
          } else if (!this.codigo_mesa.equals(valueObject.getCodigo_mesa())) {
                    return(false);
          }
          if (this.estado == null) {
                    if (valueObject.getEstado() != null)
                           return(false);
          } else if (!this.estado.equals(valueObject.getEstado())) {
                    return(false);
          }
          if (valueObject.getId_restaurante() != this.id_restaurante) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Mesa, mapping to table mesa\n");
        out.append("Persistent attributes: \n"); 
        out.append("id = " + this.id + "\n"); 
        out.append("codigo_mesa = " + this.codigo_mesa + "\n"); 
        out.append("estado = " + this.estado + "\n"); 
        out.append("id_restaurante = " + this.id_restaurante + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Mesa cloned = new Mesa();

        cloned.setId(this.id); 
        if (this.codigo_mesa != null)
             cloned.setCodigo_mesa(new String(this.codigo_mesa)); 
        if (this.estado != null)
             cloned.setEstado(new String(this.estado)); 
        cloned.setId_restaurante(this.id_restaurante); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
